services:
  vpn-server:
    build: .
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/openvpn.conf:/etc/openvpn/openvpn.conf
      - ./easy-rsa:/app/easy-rsa
    environment:
      - NODE_ENV=production
      - VPN_SUBNET=10.8.0.0
      - VPN_NETMASK=255.255.255.0
      - VPN_CONFIG_DIR=/etc/openvpn

    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped