services:
  vpn-server:
    build: .
    container_name: family-vpn-server
    user: "0:0"  # Run as root for VPN functionality
    ports:
      - "1194:1194/udp"
      - "3000:3000/tcp"
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./easy-rsa:/app/easy-rsa
      - vpn-certificates:/app/certificates
    environment:
      - VPN_SUBNET=10.8.0.0
      - VPN_NETMASK=255.255.255.0
      - VPN_CONFIG_DIR=/app/config
      - VPN_CERT_DIR=/app/certificates
      - VPN_HOST=127.0.0.1
      - LOG_DIR=/app/logs
      - LOGGER=0
      - DOCKER_ENV=true
    env_file:
      - .env
    restart: unless-stopped
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vpn-certificates:
    driver: local
  vpn-logs:
    driver: local